### ISSUE TITLE
Cannot find module

### ISSUE THREAD

**Issue by YorkAARGH** [dispix/deep-diff#1]
I'm currently developing a node application and when I try to launch with your module installed it throws the following error

```
module.js:471
    throw err;
    ^

Error: Cannot find module './utils/arrayEquals'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\Users\YorkAARGH\Desktop\Tutorial-Bot\node_modules\return-deep-diff\dist\main.js:9:20)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
```

I honestly have no idea how to fix this, but I thought you should know.

I'm running node v6.8.0 and npm 3.10.8 if that helps.

**Comment by dispix** [comment]
Thanks for the warning, found out where it comes from and am working on a fix.

**Comment by YorkAARGH** [comment]
nice! I really want to use this as well!

**Comment by dispix** [comment]
I just published v0.2.5 on Git and NPM. This should fix the export issue but I'd appreciate if you could confirm it :)

**Comment by YorkAARGH** [comment]
I will do when I get on!

**Comment by YorkAARGH** [comment]
Can confirm it is fixed and working!
